version: '2'
services:
  tools:
    extends:
      file: docker-compose.yml
      service: tools
  db:
    extends:
      file: docker-compose.yml
      service: db
  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
  liaceservice:
    image: 'lambdalab/liaceservice:0.1'
    network_mode: host
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
  metadataservice:
    image: 'lambdalab/metadataservice:0.1'
    network_mode: host
    depends_on:
      - db
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
  jenkins:
    image: 'lambdalab/jenkins:0.1'
    environment:
     - TOOLS_MOUNT=--volumes-from=tools
     - HOST_JOBS=${PWD}/data/jenkins_home/jobs
     - CACHE_DIR=artifacts
    volumes:
     - ./data/editor_projects:/lambda_home/data/editor_projects # same as editorserver
     - ./data/jenkins_home/jobs:/var/jenkins_home/jobs
     - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
     - tools
    network_mode: host
  editorserver:
    image: 'lambdalab/editorserver:0.1'
    network_mode: host
    depends_on:
      - db
      - jenkins
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
      - ./data/editor_projects:/lambda_home/data/editor_projects # same as jenkins
volumes:
  db_volume: # used for mac and windows only
    external: false