version: '2'
services:
  tools:
    extends:
      file: docker-compose.yml
      service: tools
  db:
    extends:
      file: docker-compose.yml
      service: db
  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch
  liaceservice:
    image: 'lambdalab/liaceservice:0.2.1'
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
  metadataservice:
    image: 'lambdalab/metadataservice:0.2.1'
    depends_on:
      - db
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
    ports:
      - 10060:10060
  jenkins:
    image: 'lambdalab/jenkins:0.1'
    environment:
      - TOOLS_MOUNT=--volumes-from=tools
      - HOST_JOBS=${PWD}/data/jenkins_home/jobs
    volumes:
      - ./data/editor_projects:/lambda_home/data/editor_projects # same as editorserver
      - ./data/jenkins_home/jobs:/var/jenkins_home/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - tools
    ports:
      - 8080:8080
      - 50000:50000
  editorserver:
    image: 'lambdalab/editorserver:0.2.1'
    depends_on:
      - db
      - jenkins
    ports:
      - 9030:9030
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
      - ./data/editor_projects:/lambda_home/data/editor_projects # same as jenkins
