version: '2'
services:
  tools:
    image: 'registry.lambdalab.io/lambdalab/tools:0.1.1'
    container_name: 'tools'
    volumes:
      - /lambda_home/
  db:
    image: 'registry.lambdalab.io/library/mongo:3.2'
    entrypoint:
      - mongod
      - --dbpath
      - /data/db
      - --logpath
      - /logs/mongo.log
      - --httpinterface
      - --rest
      - --setParameter
      - failIndexKeyTooLong=false
    volumes:
      - ./data/mongodb/db:/data/db
      - ./logs/mongodb:/logs
    ports:
      - 27017:27017 # TODO hide this port in the future
      - 28017:28017
  redis: # TODO mount redis disk volume
    image: 'registry.lambdalab.io/library/redis:3.2'
    command:
      - --bind 0.0.0.0
  elasticsearch:
    image: 'registry.lambdalab.io/lambdalab/elasticsearch:0.1.1'
    volumes:
      - ./data/elasticsearch:/lambda_home/data/elasticsearch
      - ./configs:/lambda_home/configs
      - ./logs/elasticsearch:/lambda_home/data/logs
    ports:
      - 9200:9200
  jenkins:
    image: 'registry.lambdalab.io/lambdalab/jenkins:0.1'
    environment:
      - TOOLS_MOUNT=--volumes-from=tools
      - HOST_JOBS=${PWD}/data/jenkins_home/jobs
    volumes:
      - ./data/jenkins_home/jobs:/var/jenkins_home/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - tools
    ports:
      - 8080:8080
      - 50000:50000
  dataservice:
    image: 'registry.lambdalab.io/lambdalab/dataservice:0.1.1'
    depends_on:
      - db
    volumes:
      - ./data/projects:/lambda_home/data/projects
      - ./logs:/lambda_home/logs
      - ./configs:/lambda_home/configs
  projectservice:
    image: 'registry.lambdalab.io/lambdalab/projectservice:0.1.1'
    depends_on:
      - db
    environment:
      - JAVA_OPTS=-Dvars.jenkins.dockerImage=registry.lambdalab.io/lambdalab/build_environment
    volumes:
      - ./data/projects:/lambda_home/data/projects
      - ./logs:/lambda_home/logs
      - ./configs:/lambda_home/configs
      - ~/.ssh:/root/.ssh
  liaceservice:
    image: 'registry.lambdalab.io/lambdalab/liaceservice:0.1.1'
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
  metadataservice:
    image: 'registry.lambdalab.io/lambdalab/metadataservice:0.1.1'
    depends_on:
      - db
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
    ports:
      - 10060:10060
  pygments:
    image: 'registry.lambdalab.io/lambdalab/pygments:0.1.1'
    depends_on:
      - db
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
  codatlas:
    image: 'registry.lambdalab.io/lambdalab/codatlas:0.1.1'
    depends_on:
      - db
      - redis
    volumes:
      - ./configs:/lambda_home/configs
      - ./logs:/lambda_home/logs
    ports:
      - 9000:9000
  nginx:
    image: 'registry.lambdalab.io/library/nginx'
    depends_on:
      - codatlas
    ports:
      - 80:80
    volumes:
      - ./sites-available:/etc/nginx/conf.d
      - ./docs:/lambda_home/docs
      - ./plugins:/lambda_home/plugins
  build_env:
    image: 'registry.lambdalab.io/lambdalab/build_environment:latest'
